# fly.toml app configuration file generated for experts-panel on 2025-10-28T01:06:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'experts-panel'
primary_region = 'iad'

[env]
  MAP_MAX_PARALLEL = "5"
  ENVIRONMENT = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = 'experts_data'
  destination = '/app/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1